### PR TITLE
Add data models - DTOs and Entities

### PR DESCRIPTION
**Pull request by PhilipGlover**
Models for PSC individual as we understand at present

PSC-54

### CODE REVIEW

**Comment by hepsimo** [comment]
**NOTE** This PR added a unit test but the analysis is not picking up any coverage.

I suspect that may be because
1. The pipeline log for sonar step has this:
```[INFO] Project configuration:
[INFO]   Excluded sources for coverage: **/models/**/*.java, **/data/**/*.go, **/model/**/*.java, static/javascripts/**/*, static/javascript/**/*, static/css/**/*, templates/**/*, **/scripts/**
[INFO]   Excluded sources for duplication: **/models/**/*.java, **/model/**/*.java, **/data/**/*.go
```
2. these exclusions are not defined in our project POM or its parent POM
3. i suspect that the exclusions are set on the Sonar project (server) -- inherited as defaults?
4. our model code happens to be in a `model` package so matches the wildcard path `**/model/**/*.java` above

Perhaps we should rename our package to avoid the exclusions: e.g. `data-model`

**Comment by hepsimo** [comment]
Recommend we refine these models following further work @eedwards0 is doing to capture the 3 PSC types in the model.

**Comment by PhilipGlover** [comment]
models further refined and Mapper class moved out of model package so that tests are picked up for coverage in Sonar

**Review by clewis1 — APPROVED** [review]
Looks good

**Pull request merged**
